config/routes.rb
Rails.application.routes.draw do
  get 'register', to: 'application#register'
  resources :charges
  resources :pricetags
  devise_for :users
  root 'application#index'
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  attr_accessor :amount, :description, :email
  validates_presence_of :amount, :description, :email
  validates_numericality_of :amount
end

app/models/pricetag.rb
class Pricetag < ActiveRecord::Base
  validates_presence_of :amount, :description
  validates_uniqueness_of :amount, :description
  
  def amount=(a)
    b = a.split('.')
    write_attribute(:amount, a.to_s.include?('.') ? b.first + b.last : a)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  	@charge = Charge.new
    @pricetags = Pricetag.order("amount")
  end
  
  def register
    
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @charge = Charge.new
  end

  def create
    @charge = Charge.new(charge_params)
    if @charge.amount == '0'
      redirect_to root_url, notice: 'You must enter a donation amount.'
    else
      customer = Stripe::Customer.create(
        card:         params[:stripeToken],
        email:        @charge.email, 
        description:  request.ip
      )
      charge = Stripe::Charge.create(
        customer:     customer.id,
        amount:       @charge.amount,
        description:  @charge.description,
        currency:     'usd'
      )
    end
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_url
  end
 
  def charge_params
    params.require(:charge).permit(:amount, :description, :email)
  end
  
end

app/controllers/pricetags_controller.rb
class PricetagsController < ApplicationController
  before_action :set_pricetag, only: [:edit, :update, :destroy]
  #before_filter :authenicate_lord!
  
  def index
    @pricetags = Pricetag.all
  end
  def new
    @pricetag = Pricetag.new
  end
  def edit
  end
  def create
    @pricetag = Pricetag.new(pricetag_params)
    respond_to do |format| 
      if @pricetag.save
        format.html { redirect_to pricetags_url }
      else
        format.html { render action: 'new' }
      end
    end
  end
  def update
    respond_to do |format| 
      if @pricetag.update(pricetag_params)
        format.html { redirect_to pricetags_url }
      else
        format.html { redirect_to pricetags_url }
      end
    end
  end
  def destroy
    @pricetag.destroy
    respond_to do |format| 
      if @pricetag.save
        format.html { redirect_to pricetags_url }
      else
        format.html { redirect_to pricetags_url }
      end
    end
  end
  private
    def set_pricetag
      @pricetag = Pricetag.find(params[:id])
    end
    def pricetag_params
      params.require(:pricetag).permit(:amount, :description)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
	def glyph(icon)
		"<span class='glyphicon glyphicon-#{icon}'></span>".html_safe
	end
  def resource_name
    :user
  end
  def resource
    @resource ||= User.new
  end
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pricetags_helper.rb
module PricetagsHelper
end

app/views/application/index.html.erb
<div class="pricetags-container">
	<h3>Select a Pricetag or make a Donation</h3>
	<%= render 'charges/new' %>
	<br/>
	<h3>Use this fake/demo credit card:</h3>
	<div class="credit-card">
		Card: <span class="number">4242 4242 4242 4242</span>
		<span class="security-code">CVC: <strong>123</strong></span>
		Expiration: <span class="expiration">(Any Future Date)</span>
	</div>
</div>

app/views/application/register.html.erb
<div class="register-page">
	<div class="pull-left fifty">
		<%= render 'devise/registrations/signup' %>
	</div>
	<div class="pull-right fifty">
		<%= render 'devise/sessions/signin' %>
	</div>
	<div class="clearfix"></div><br/>
	<div class="demo-account">email: <strong>user@demo.com</strong> password: <strong>password</strong>
</div>

app/views/charges/_custom.html.erb
<%= simple_form_for @charge do |f| %>
  <%= f.hidden_field :amount, value: nil %>
	<%= f.hidden_field :description, value: nil %>
	<%= render 'custom_form' %>
<% end %>
	


	  
	

	

	

app/views/charges/_custom_form.html.erb
<div class="donation-option">
	<a>Custom Amount<br>(in dollars and cents)</a> 
	<div class="input-group pad">
  	<span class="input-group-addon">$</span>
		<%= text_field_tag 'amount', nil, id: 'custom_amount', class: 'form-control', placeholder: 'Ex: 25.00' %>
	</div>
	<%= f.button :submit, disabled: true, class: 'hide' %>
	<%= link_to 'Make Donation', '#', id: 'pricetag_custom',
	    class: 'btn btn-warning form-control' %>
</div>

<script>
$('#pricetag_custom').click(function(){
  var token = function(token, args){
    var $input = $('<input type=hidden name=stripeToken />').val(token.id);
		$('#charge_amount').val($('#custom_amount').val() * 100);
		$('#charge_description').val('Donation');
		$('#charge_email').val(token.email);
    $('form').append($input).submit();
  };
	var amount = ($('#custom_amount').val() * 100);
  StripeCheckout.open({
    key:         '<%= STRIPE_PUBLIC_KEY %>',
    address:     false,
    amount:      amount,
    currency:    'usd',
    name:        'The Nations Group',
    description: 'Donation',
    panelLabel:  'Donate',
		email:       '<%= current_user ? current_user.email : '' %>',
    token:       token
  });
  return false;
});
</script>

app/views/charges/_new.html.erb
<%= simple_form_for @charge do |f| %>
  <%= f.hidden_field :amount, value: nil %>
	<%= f.hidden_field :description, value: nil %>
	<%= f.hidden_field :email, value: nil %>
	<% @pricetags.each do |pricetag| %>
		<div id="pricetag_<%=pricetag.id%>" class="pricetag-option">
			$<%= pricetag.amount / 100 %><br><span class="details">Make Payment</span>
		</div>
		
	  <script>
    $('#pricetag_<%=pricetag.id%>').click(function(){
      var token = function(token, args){
        var $input = $('<input type=hidden name=stripeToken />').val(token.id);
				$('#charge_amount').val('<%= pricetag.amount %>');
				$('#charge_description').val('<%= pricetag.description %>');
				$('#charge_email').val(token.email);
        $('form').append($input).submit();
      };
      StripeCheckout.open({
        key:         '<%= STRIPE_PUBLIC_KEY %>',
        address:     false,
        amount:      '<%= pricetag.amount %>',
        currency:    'usd',
        name:        'Stripe Payments Demo',
        description: '<%= pricetag.description %>',
        panelLabel:  'Pay',
		    email:       '<%= current_user ? current_user.email : '' %>',
        token:       token
      });
      return false;
    });
	  </script> 
		
	<% end %>
	<%= render 'charges/custom_form', f: f %>
<% end %>



	


	

	

app/views/charges/create.html.erb
<script>  
var count =3  
var redirect="<%= root_path %>"
  
function countDown(){  
 if (count <=0){  
  window.location = redirect;  
 }else{  
  count--;  
  document.getElementById("timer").innerHTML = "This page will redirect in "+count+" seconds."  
  setTimeout("countDown()", 1000)  
 }  
}  
</script>  

<div class="thanks">
  Thank you for!
</div>

<span id="timer" style="display:none;">  
<script>  
 countDown();  
</script>  
</span>  

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <%= link_to 'Stripe Payments Demo', root_path, class: 'navbar-brand' %>
</div>
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
		<% if current_user %>
			<%= link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do %>
			  <%= current_user.email %> <%= glyph('cog') %>
			<% end %>
		<% else %>
			<%= link_to glyph('cog'), '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } %>
		<% end %>
    <ul class="dropdown-menu" role="menu">
	  <% if current_user %>
        <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
				<li><%= link_to 'Sign out now', destroy_user_session_path, method: :delete %></li>
	  <% else %>
        <li><%= link_to 'Sign in/Sign up', register_path %></li>
	  <% end %>
 	  <li class="divider"></li>
      <li><%= link_to 'Change Pricetags', pricetags_path %></li>
    </ul>
  </li>
</ul>

      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StripePaymentsDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <nav class="navbar navbar-fixed-top" role="navigation">
		 <div class="container-fluid">
       <%= render 'layouts/navigation' %>
     </div>
	</nav>
	<div id="main" role="main">
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div> 
  </div> 
</body>
</html>

app/views/pricetags/_form.html.erb
<%= simple_form_for @pricetag do |f| %>
  <%= f.error_notification %>
	<div class="input-group">
	  <span class="input-group-addon">$</span>
	  <%= f.text_field :amount, class: 'form-control', placeholder: 'Amount (ex: 25.00)' %>
	</div><br>
	<%= f.text_field :description, class: 'form-control', placeholder: 'Description (ex: $25 Payment)' %><br>
	<%= link_to 'Go Back', root_path, class: 'btn btn-default' %>
	<%= f.button :submit, "Save", class: 'btn btn-warning' %>
<% end %>

app/views/pricetags/edit.html.erb
<div id="pricetag_form_container">
	<h3>Edit Pricetag Amount</h3>
	<br>
	<%= render 'form' %>
</div>

app/views/pricetags/index.html.erb
<div class="pricetag-table">
	<h3>Listing Pricetags</h3><a>(Click to edit)</a>
	<br><br>
	<table class="table">
		<thead>
			<th>Amount (in cents)</th>
			<th>Description</th>
			<th>Delete</th>
		</thead>
	<% @pricetags.each do |pricetag| %>
		<tbody>
			<tr>
				<td><%= link_to "#{pricetag.amount}&nbsp;&nbsp;Cents".html_safe, edit_pricetag_path(pricetag) %></td>
	  		<td><%= link_to pricetag.description, edit_pricetag_path(pricetag) %></td>
				<td><%= link_to 'Delete', pricetag, method: :delete, data: { confirm: 'Delete Pricetag?' }, class: 'btn-sm btn-default' %></td>
			</tr>
		</tbody>
	<% end %>
</table>
<%= link_to 'Create New Pricetag', new_pricetag_path, class: 'btn btn-default' %>
</div>

app/views/pricetags/new.html.erb
<div id="pricetag_form_container">
	<h3>Create Pricetag</h3>
	<br>
	<%= render 'form' %>
</div>